[package]
name = "email-sender-rust"
version = "0.2.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = true
codegen-units = 1

[dependencies]
# This openssl with "vendored" is necessary because the default OpenSSL library is not built for the target architecture (x86_64-unknown-linux-musl)
openssl = { version = "0.10.52", features = ["vendored"] }
actix-cors = "0.6.4"
actix-web = "4.3.1"
dotenvy = "0.15.7"
lambda-web = { version = "0.2.1", features = ["actix4"] }
log = "0.4.17"
sendgrid_thin = { version = "0.4.5", default-features = false }
sentry = "0.31.0"
serde = { version = "1.0.160", features = ["derive"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde_json = "1.0.96"
sentry-actix = "0.31.0"
reqwest = "0.11.16"
unicode-segmentation = "1.10.1"
tokio = "1.28.0"
